const COLOR_LITE = {
  CRAYOLA: '#e9c46a',
  PASTEL: '#e5989b',
  ORANGE: '#fca311'
}
const COLOR_DARK = {
  CHARCOAL: '#264653',
  PERSIAN: '#2a9d8f',
  SIENNA: '#e76f51'
}
const COLOR_LITE_VALUE = Object.values(COLOR_LITE)
const COLOR_DARK_VALUE = Object.values(COLOR_DARK)
export { COLOR_LITE, COLOR_DARK, COLOR_LITE_VALUE, COLOR_DARK_VALUE }
